---
title: "Generate Edge Lists"
author: "Lauren White"
date: "April 10, 2018"
output: html_document
---

##Load data
```{r} 
setwd("C:/Users/law2y/OneDrive/R Code/FrogNetworks")
cwc<-read.csv("CountsWithComplexes.csv")
cwoc<-read.csv("CountsWithoutComplexes.csv")

#drop columns that got imported for csv files for some reason
cwc <- subset(cwc, select = -c(X,X.1) ) 
cwoc <- subset(cwoc, select = -c(X,X.1) )


unique(cwc$Species.ID) #how many unique species?
length(unique(cwc$Transect))
dates<-unique(cwc$Date)

#create separate column that combines transect + stop location
cwc$transectstop<- paste(cwc$Transect,cwc$Stop, sep="-") 
cwoc$transectstop<- paste(cwoc$Transect,cwoc$Stop, sep="-")

```

##Generate edgelist
Which species have called on same date at same transect & stop?
Beware: this takes a while to run.

```{r, eval=FALSE}
dates<-unique(cwc$Date) #how many dates of observation in dataset?

#With complexes
edgelist<-NULL

for(i in 1:length(dates)){
  sub_cwc<-cwc[which(cwc$Date==dates[i]),]
  edgelist_sub<-data.frame(Species=sub_cwc$Species, Location=sub_cwc$transectstop)
  edgelist<-rbind(edgelist, edgelist_sub)
  #browser()
}
write.csv(edgelist,file="frogedgelist.csv")

#Without complexes
dates<-unique(cwoc$Date) #how many dates of observation in dataset?
edgelist<-NULL

for(i in 1:length(dates)){
  sub_cwoc<-cwoc[which(cwoc$Date==dates[i]),]
  edgelist_sub<-data.frame(Species=sub_cwoc$Species, Location=sub_cwoc$transectstop)
  edgelist<-rbind(edgelist, edgelist_sub)
  #browser()
}
write.csv(edgelist,file="frogedgelist_cwoc.csv")
```

Or load edgelist
```{r}
edgelist<-read.csv("frogedgelist.csv")
#edgelist<-read.csv("frogedgelist_cwoc.csv")
```
